# This is a basic workflow to help you get started with Actions
name: gh-deploy

on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: MkDocs Github Pages automatic deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: build jupyter-book and copy to gh-pages branch
        run: |
          pip install jupyter-book ghp-import
          jupyter-book build ./    
          ghp-import -n -p -f _build/html             


